language: scala
scala:
  - 2.10.6
  - 2.11.8
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - sbt ++$TRAVIS_SCALA_VERSION 'docs/tut'
after_success:
- sbt ++$TRAVIS_SCALA_VERSION coverageReport
- bash <(curl -s https://codecov.io/bash) -t 744f05ba-f905-4468-aef1-f5016fc2909d
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    sbt ++$TRAVIS_SCALA_VERSION publishSigned;
  fi