language: scala
dist: trusty
jdk:
  - oraclejdk11

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_88322e86f6b6_key -iv $encrypted_88322e86f6b6_iv -in secring.gpg.enc -out secring.gpg -d;
  fi
- export PATH=${PATH}:./vendor/bundle

install:
- rvm use 2.6.5 --install --fuzzy
- yes | gem update --system --force
- gem install sass
- gem install jekyll -v 4.0.0

stages:
- test
- deploy

after_success:
- bash <(curl -s https://codecov.io/bash)

jobs:
  include:
    - script:
        - sbt ++$TRAVIS_SCALA_VERSION $SBT_JAVA_OPT validate;
        - sbt ++$TRAVIS_SCALA_VERSION $SBT_JAVA_OPT docs/tut;
    - stage: deploy
      script:
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
            if grep -q "SNAPSHOT" version.sbt; then
              sbt ++$TRAVIS_SCALA_VERSION publish;
            else
              sbt orgUpdateDocFiles;
              git reset --hard HEAD;
              git clean -f;
              git checkout master;
              git pull origin master;
              sbt release;
              sbt docs/publishMicrosite;
            fi
          fi
      scala: 2.12.10

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - $HOME/.sbt/1.0/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.nvm
