language: scala
dist: trusty
jdk:
  - oraclejdk11

scala:
  - 2.12.10
  - 2.13.1

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_88322e86f6b6_key -iv $encrypted_88322e86f6b6_iv -in secret_key.asc.enc -out secret_key.asc -d;
    gpg --import --batch --passphrase "$PGP_PASSPHRASE" secret_key.asc;
  fi
- export PATH=${PATH}:./vendor/bundle

install:
- rvm use 2.6.5 --install --fuzzy
- gem install jekyll -v 4

script:
- sbt ++$TRAVIS_SCALA_VERSION test

stages:
- test
- docs
- deploy

jobs:
  include:
    - stage: docs
      scala: 2.12.10
      script:
        - sbt ++$TRAVIS_SCALA_VERSION docs/mdoc
        - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport coverageAggregate
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      scala: 2.12.10
      script:
        - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
            if grep -q "SNAPSHOT" version.sbt; then
              sbt ++$TRAVIS_SCALA_VERSION publish;
            else
              sbt orgUpdateDocFiles;
              git reset --hard HEAD;
              git clean -f;
              git checkout master;
              git pull origin master;
              sbt release;
              sbt docs/publishMicrosite;
            fi
          fi

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

cache:
  directories:
  - $HOME/.sbt/1.0/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.nvm
