language: scala

scala:
- 2.10.6
- 2.11.11
- 2.12.2

jdk:
- oraclejdk8

before_install:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    openssl aes-256-cbc -K $encrypted_88322e86f6b6_key -iv $encrypted_88322e86f6b6_iv -in secring.gpg.enc -out secring.gpg -d;
  fi

script:
- sbt ++$TRAVIS_SCALA_VERSION orgScriptCI

after_success:
- bash <(curl -s https://codecov.io/bash) -t 744f05ba-f905-4468-aef1-f5016fc2909d
- sbt ++$TRAVIS_SCALA_VERSION orgAfterCISuccess